config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  root 'experts#index'

  namespace :api, defaults: { format: "json" } do
    namespace :v1 do
      resources :experts, only: [:index, :show]
      resources :categories, only: [:index]
      resources :contacts, only: [:index]

      resource :profile, only: [:show, :create, :update] do
        post :pushtoken
        post :location
      end

      resources :message, only: [:show] do
        member do
          post :create
        end
        collection do
          get :unread
        end
      end
    end
  end

  namespace :admin do
    get "/login", to: "login#new"
    post "/login", to: "login#create"
    get "/approve", to: "approve#index"
    post "/approve", to: "approve#update"
    get "/applicants", to: "applicants#index"
  end

  get '/auth/twitter/callback', to: "sessions#create"

  get "onboarding/step/1", to: "onboarding#step1"
  get "onboarding/step/2", to: "onboarding#step2"
  post "onboarding/step/2", to: "onboarding#step2_submit"
  get "onboarding/step/3", to: "onboarding#step3"
  post "onboarding/step/3", to: "onboarding#step3_submit"
  get "onboarding/success", to: "onboarding#success"

  get "about", to: "landing#about"
  get "landing", to: "landing#index"
  get "faq", to: "landing#faq"

  get 'berlin/:id', to: redirect('/')
  get 'prelaunch', to: redirect('/')
  get 'Prelaunch', to: redirect('/')
  get '/uploads/user/000/000/347/photo/158c4278a1.png', to: redirect('/')

  resources :users, path: '', only: [:show, :edit, :update], constraints: { id: /@[\w-]+/ }
  resources :web_messages, only: [:create]

  get "/experts", to: "experts#index"
  get "/experts/:category", to: "experts#index", as: :category_experts
  get "/experts/:category/:city", to: "experts#index", as: :category_city_experts

  get "logout", to: "sessions#destroy"
end

app/models/user.rb
class User < ActiveRecord::Base
  include Messageable
  include Redis::Objects

  has_one  :skill, dependent: :destroy
  has_many :user_friended_experts
  has_many :user_followers, foreign_key: :expert_id, class_name: 'UserFriendedExpert', dependent: :destroy

  validates_presence_of :full_name, :photo, :email, :job
  validates :job, length: { maximum: 40 }
  validates :about, length: { maximum: 500 }
  # validates :email, email: true

  before_validation :add_protocol_for_urls

  # TODO extremely bad style, need to fix it somehow
  def add_protocol_for_urls
    URLS.each do |url|
      if self.send(url).present? && self.send(url) != ""
        unless self.send(url)[/\Ahttp:\/\//] || self.send(url)[/\Ahttps:\/\//]
          self.send("#{url}=", "http://#{self.send(url)}")
        end
      end
    end
  end

  scope :with_category, -> category { joins(skill: :tags).where("tags.is_category" => true, "tags.name" => category) }
  scope :with_any_category, -> category { joins(skill: :tags).where("tags.name" => category) }
  scope :with_any_new_category, -> category { joins(:skill).where("skills.category = ?", Skill.categories[category]) }
  
  scope :developers, -> { with_any_new_category("Developer") }
  scope :designers, -> { with_any_new_category("Designer") }
  scope :business, -> { with_any_new_category("Business Consultant") }
  scope :marketers, -> { with_any_new_category("Marketer") }
  scope :creatives, -> { with_any_new_category("Creative") }

  scope :from_twitter, -> { where.not('users.twitter_id' => nil) }
  scope :unapproved, -> { where(approved: false) }
  scope :approved, -> { where(approved: true) }
  scope :not_featured, -> { where(is_featured: false) }
  scope :featured, -> { where(is_featured: true) }
  scope :experts, -> { joins(:skill) }
  scope :near_user, -> user {
    geocoded.
    near([user.latitude, user.longitude], user.max_search_distance).
    reorder('') # we didn't ask to sort by distance
  }
  scope :by_rating, -> user {
    near_user(user).
    include_is_followed(user).
    # intermediate_followers_count(user).
    order('is_followed DESC').
    # order('intermediate_followers_count DESC'). # not using this just yet
    order(social_authority: :desc).
    order('distance DESC').
    order(created_at: :desc)
  }
  # duplication, change later
  scope :by_rating_for_view, -> user {
    # include_is_followed(user).
    # # intermediate_followers_count(user).
    # order('is_followed DESC').
    # order('intermediate_followers_count DESC'). # not using this just yet
    order(social_authority: :desc).
    order(created_at: :desc)
  }
  scope :by_authority, -> { order("social_authority desc, users.created_at desc") }
  scope :include_is_followed, -> user {
    joins("LEFT OUTER JOIN user_friended_experts ON user_friended_experts.expert_id = users.id AND user_friended_experts.user_id = #{user.id}").
    select('COUNT(user_friended_experts) as is_followed').
    group('users.id')
  }
  # scope :include_intermediate_followers_count, -> user {
  #   joins("LEFT OUTER JOIN user_friended_expert_followers ON user_friended_expert_followers.expert_id = users.id AND user_friended_expert_followers.user_id = #{user.id}").
  #   select('COUNT(user_friended_expert_followers) as intermediate_followers_count').
  #   group('users.id')
  # }

  geocoded_by :ip_address
  after_validation :geocode, unless: :location_defined?

  delegate :price, :smartphone_os, :category,
           to: :skill,
           allow_nil: true

  delegate :title, :tags, :tags_text, :categories, :categories_text,
           to: :skill,
           prefix: true,
           allow_nil: true

  accepts_nested_attributes_for :skill

  URLS = %w[website_url twitter_url facebook_url linkedin_url behance_url github_url stackoverflow_url angellist_url dribble_url]

  store_accessor :urls, *URLS

  extend FriendlyId
  friendly_id :full_name, use: :slugged

  mount_uploader :photo, UserPhotoUploader
  mount_uploader :profile_banner, UserBannerUploader

  set :twitter_friends
  set :twitter_followers

  def first_name
    full_name.split(/\s+/).select { |part| part.present? }.first
  end

  def expert?
    skill.present?
  end

  def admin?
    role == "admin"
  end

  def approve
    self.approved = true
    self.save(validate: false)
  end

  def self.admin
    where(role: "admin").first
  end

  def self.find_by_handle(handle)
    where("lower(twitter_handle) = ?", handle.downcase).first
  end

  def update_location location, ip
    if location
      self.latitude = location.latitude
      self.longitude = location.longitude
    end
    self.ip_address = ip
    save
  end

  def location_defined?
    self.latitude && self.longitude
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authenticate!, only: [:show]
  before_action :set_user

  def show
    authorize! :read, @user
  end

  def edit
    authorize! :update, @user
  end

  def update
    authorize! :update, @user

    if @user.update(user_params.except(:skill_attributes)) && SkillCreator.new(@user).create(user_params[:skill_attributes])
      redirect_to user_path("@#{@user.twitter_handle}")
    else
      render "edit"
    end
  end

private

  def user_params
    params.require(:user).permit(
      :full_name, :email, :job, :about, :photo, :profile_banner, :profile_banner_cache,
      :website_url, :facebook_url, :github_url, :behance_url,
      :stackoverflow_url, :linkedin_url,
      skill_attributes: [:title, :price, :tags_text, :category]
    )
  end

  def set_user
    handle = params[:id].match /@([\w-]+)/

    @user = User.find_by_handle(handle[1])
  end
end

app/views/users/edit.html.slim
- title "Edit profile"

section.onboarding-step
  header
    h2 Edit Your Profile

    = simple_form_for @user, url: user_path("@#{@user.twitter_handle}"), method: :put, html: { multipart: true } do |f|
      fieldset
        = f.input :photo, as: :image_upload, label: false, input_html: { class: "photo" }
        = f.input :full_name
        = f.input :email
        = f.input :job
        = f.input :about
        = f.input :profile_banner, as: :image_upload, input_html: { class: "banner" }
        = f.hidden_field :profile_banner_cache

        a.add-social href='#' + Add your social networks
        .social-networks
          = f.input :website_url
          = f.input :facebook_url
          = f.input :github_url
          = f.input :behance_url
          = f.input :stackoverflow_url
          = f.input :linkedin_url
      fieldset
        = f.simple_fields_for :skill do |s|
          = s.input :title, placeholder: 'Data Science Consulting — Leverage your data for a personalised user experience'
          .price
            span.dollar $
            = s.input :price
          = s.input :category, as: :radio_buttons, collection: Skill::NEW_CATEGORIES
          = s.input :tags_text, placeholder: 'Design, UX Design'
          = f.submit "Update"

app/views/users/show.html.slim
- user = @user.decorate

- page_title = expert_title(user)
- description = user.about
- image = full_url(user.photo_url)
- url = user_url("@#{user.twitter_handle}")

- title page_title, description: description, canonical: url
- set_meta_tags og: { title: title, image: image, description: description, url: url }
- set_meta_tags twitter: { title: title, image: image, description: description, url: url }

section.profile-page
  header.profile
    .bg[style="background-image: url(#{user.profile_banner_url});background-size: cover;"]
    h2.skill-title = user.skill_title
    .userpic [style="background-image: url(#{user.photo_url});background-size: cover;"]
  section.profile
    h2.name = user.full_name
    p.job = user.job
    h3.price = user.price

    - if !(current_user.present? && current_user.id == user.id)
      a.button.message-button href="#" Send a message

    - if can?(:update, user)
      = link_to "Edit profile", edit_user_path("@#{user.twitter_handle}"), class: "button"
    ul.tags = user.tags
    p.about = user.about
    .caps Social networks
    ul.urls = user.urls

.message-popup
  .icon-close
  .content
    h2 = "Send #{user.full_name} a private message."
    = simple_form_for WebMessage.new, html: {class: "message-form"} do |f|
      = f.input :full_name, placeholder: "Your name", label: false, input_html: { value: (current_user.present? && current_user.full_name) || "" }
      = f.input :email, placeholder: "Your email", label: false, input_html: { value: (current_user.present? && current_user.email) || "" }
      = f.input :expert_id, as: "hidden", input_html: { value: user.id }
      = f.input :body, label: false, input_html: { value: "Hi #{user.first_name}, I found your profile on Skillpocket and would like to hire you." }, hint: "Please be specific about your request"
      = f.submit "Send", input_html: { class: "button" }