config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  root 'experts#index'

  namespace :api, defaults: { format: "json" } do
    namespace :v1 do
      resources :experts, only: [:index, :show]
      resources :categories, only: [:index]
      resources :contacts, only: [:index]

      resource :profile, only: [:show, :create, :update] do
        post :pushtoken
        post :location
      end

      resources :message, only: [:show] do
        member do
          post :create
        end
        collection do
          get :unread
        end
      end
    end
  end

  namespace :admin do
    get "/login", to: "login#new"
    post "/login", to: "login#create"
    get "/approve", to: "approve#index"
    post "/approve", to: "approve#update"
    get "/applicants", to: "applicants#index"
  end

  get '/auth/twitter/callback', to: "sessions#create"

  get "onboarding/step/1", to: "onboarding#step1"
  get "onboarding/step/2", to: "onboarding#step2"
  post "onboarding/step/2", to: "onboarding#step2_submit"
  get "onboarding/step/3", to: "onboarding#step3"
  post "onboarding/step/3", to: "onboarding#step3_submit"
  get "onboarding/success", to: "onboarding#success"

  get "about", to: "landing#about"
  get "landing", to: "landing#index"
  get "faq", to: "landing#faq"

  get 'berlin/:id', to: redirect('/')
  get 'prelaunch', to: redirect('/')
  get 'Prelaunch', to: redirect('/')
  get '/uploads/user/000/000/347/photo/158c4278a1.png', to: redirect('/')

  resources :users, path: '', only: [:show, :edit, :update], constraints: { id: /@[\w-]+/ }
  resources :web_messages, only: [:create]

  get "/experts", to: "experts#index"
  get "/experts/:category", to: "experts#index", as: :category_experts
  get "/experts/:category/:city", to: "experts#index", as: :category_city_experts

  get "logout", to: "sessions#destroy"
end

app/views/shared/_appstrip.slim
.app-strip
  span.title Finding local talent is way better on mobile
  a.download.button href="https://itunes.apple.com/us/app/skillpocket-hire-experts/id933547324?ls=1&mt=8"
    span.icon-apple
    span Get Skillpocket for iPhone

app/views/shared/_head.slim
= favicon_link_tag
meta[name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" user-scalable="no"]
= csrf_meta_tags
= display_meta_tags

app/views/shared/_header.slim
- if current_user.present?
  - user = current_user.decorate

header.main
  = link_to root_path, class: 'logo'
    span.icon-logo
    span Skillpocket
  .menu
    a.menu-button href="#" Menu
  nav.main
    .overlay
    ul
      li
        = link_to_unless_current 'How It Works', landing_path
      li
        = link_to_unless_current 'About', about_path
      li
        = link_to_unless_current 'FAQ', faq_path
      - if current_onboarding_step.nil? && user.approved
        li = link_to_unless_current 'Profile', user_path("@#{user.twitter_handle}")
          / TODO find a clean way to define route
      - if current_onboarding_step.present?
        li
          = link_to_unless_current 'Become an expert', "/onboarding/step/#{current_onboarding_step}", class: "button become"
      - if current_onboarding_step.nil? && user.approved
        li
          = link_to_unless_current 'Profile', user_path("@#{user.twitter_handle}")
      - if signed_in?
        li = link_to 'Logout', logout_path
      - else
        li = link_to 'Login', "/auth/twitter"

app/views/shared/_mixpanel.slim
javascript:
  (function(f,b){if(!b.__SV){var a,e,i,g;window.mixpanel=b;b._i=[];b.init=function(a,e,d){function f(b,h){var a=h.split(".");2==a.length&&(b=b[a[0]],h=a[1]);b[h]=function(){b.push([h].concat(Array.prototype.slice.call(arguments,0)))}}var c=b;"undefined"!==typeof d?c=b[d]=[]:d="mixpanel";c.people=c.people||[];c.toString=function(b){var a="mixpanel";"mixpanel"!==d&&(a+="."+d);b||(a+=" (stub)");return a};c.people.toString=function(){return c.toString(1)+".people (stub)"};i="disable track track_pageview track_links track_forms register register_once alias unregister identify name_tag set_config people.set people.set_once people.increment people.append people.track_charge people.clear_charges people.delete_user".split(" ");
  for(g=0;g<i.length;g++)f(c,i[g]);b._i.push([a,e,d])};b.__SV=1.2;a=f.createElement("script");a.type="text/javascript";a.async=!0;a.src="//cdn.mxpnl.com/libs/mixpanel-2.2.min.js";e=f.getElementsByTagName("script")[0];e.parentNode.insertBefore(a,e)}})(document,window.mixpanel||[]);
  mixpanel.init("#{ENV['MIXPANEL_TOKEN']}");

app/views/shared/_profile.html.slim
- user = user.decorate

section.profile-page
  header.profile
    .bg[style="background-image: url(#{user.profile_banner_url});"]
    h2.skill-title= user.skill_title
    = image_tag user.photo_url, class: 'userpic'
  section.profile
    h2.name = user.full_name
    p.job = user.job
    h3.price = user.price
    p.tags = user.tags
    p.about = user.about
    ul.urls
      = user.urls

app/views/shared/_social.slim
noscript
  iframe src="//www.googletagmanager.com/ns.html?id=GTM-NNMSP8" height="0" width="0" style="display:none;visibility:hidden"
javascript:
  (function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start': new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src='//www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);})(window,document,'script','dataLayer','GTM-NNMSP8');